### ISSUE TITLE
Error on master

### ISSUE THREAD

**Issue by florian-vuillemot** [florian-vuillemot/homerV2#46]
When you run test:
1) test create project renders errors when step are not in number (HomerWeb.Bu                                                                                                                                  ilders.ProjectControllerTest)
     test/homer_web/controllers/builders/project_controller_test.exs:84
     ** (RuntimeError) expected response with status 422, got: 401, with body:
     {"errors":["Unauthenticated"]}
     code: assert json_response(conn, 422)["errors"] != %{}
     stacktrace:
       (phoenix) lib/phoenix/test/conn_test.ex:362: Phoenix.ConnTest.response/2
       (phoenix) lib/phoenix/test/conn_test.ex:408: Phoenix.ConnTest.json_respon                                                                                                                                  se/2
       test/homer_web/controllers/builders/project_controller_test.exs:89: (test                                                                                                                                  )

**Comment by florian-vuillemot** [comment]
Test was not update for sending connexion token.
